/// Time, speed, angle and frequency.
library;

import '../unit.dart';

const timeUnits = <Unit>[
  Unit(
    id: 'second',
    name: 'Second',
    symbol: 's',
    category: UnitCategory.time,
    toBase: '1',
    aliases: ['seconds', 'sec', 'secs', 's'],
  ),
  Unit(
    id: 'millisecond',
    name: 'Millisecond',
    symbol: 'ms',
    category: UnitCategory.time,
    toBase: '0.001',
    aliases: ['milliseconds', 'ms'],
  ),
  Unit(
    id: 'microsecond',
    name: 'Microsecond',
    symbol: 'µs',
    category: UnitCategory.time,
    toBase: '0.000001',
    aliases: ['microseconds', 'us'],
  ),
  Unit(
    id: 'nanosecond',
    name: 'Nanosecond',
    symbol: 'ns',
    category: UnitCategory.time,
    toBase: '1/10^9',
    aliases: ['nanoseconds', 'ns'],
  ),
  Unit(
    id: 'minute',
    name: 'Minute',
    symbol: 'min',
    category: UnitCategory.time,
    toBase: '60',
    aliases: ['minutes', 'min', 'mins'],
  ),
  Unit(
    id: 'hour',
    name: 'Hour',
    symbol: 'h',
    category: UnitCategory.time,
    toBase: '3600',
    aliases: ['hours', 'hr', 'hrs', 'h'],
  ),
  Unit(
    id: 'day',
    name: 'Day',
    symbol: 'd',
    category: UnitCategory.time,
    toBase: '86400',
    aliases: ['days', 'd'],
  ),
  Unit(
    id: 'week',
    name: 'Week',
    symbol: 'wk',
    category: UnitCategory.time,
    toBase: '604800',
    aliases: ['weeks', 'wk'],
  ),
  Unit(
    id: 'fortnight',
    name: 'Fortnight',
    symbol: 'fn',
    category: UnitCategory.time,
    toBase: '1209600',
    aliases: ['fortnights'],
  ),
  Unit(
    id: 'month',
    name: 'Month (average)',
    symbol: 'mo',
    category: UnitCategory.time,
    // A twelfth of a Julian year. Real months are 28–31 days.
    toBase: '365.25*86400/12',
    aliases: ['months', 'mo'],
    note: 'An average month of 30.44 days. Calendar months vary from 28 '
        'to 31, so use a date calculation where the exact month matters.',
  ),
  Unit(
    id: 'year',
    name: 'Year (Julian)',
    symbol: 'yr',
    category: UnitCategory.time,
    toBase: '365.25*86400',
    aliases: ['years', 'yr', 'yrs', 'julian year'],
    note: 'The Julian year of 365.25 days, which is what astronomy and '
        'the light year use.',
  ),
  Unit(
    id: 'year_common',
    name: 'Year (common, 365 days)',
    symbol: 'yr',
    category: UnitCategory.time,
    toBase: '365*86400',
    aliases: ['common year', 'calendar year'],
  ),
  Unit(
    id: 'decade',
    name: 'Decade',
    symbol: 'dec',
    category: UnitCategory.time,
    toBase: '10*365.25*86400',
    aliases: ['decades'],
  ),
  Unit(
    id: 'century',
    name: 'Century',
    symbol: 'c',
    category: UnitCategory.time,
    toBase: '100*365.25*86400',
    aliases: ['centuries'],
  ),
  Unit(
    id: 'millennium',
    name: 'Millennium',
    symbol: 'ka',
    category: UnitCategory.time,
    toBase: '1000*365.25*86400',
    aliases: ['millennia', 'millenniums'],
  ),
];

const speedUnits = <Unit>[
  Unit(
    id: 'metre_per_second',
    name: 'Metre per second',
    symbol: 'm/s',
    category: UnitCategory.speed,
    toBase: '1',
    aliases: ['metres per second', 'meters per second', 'm/s', 'mps'],
  ),
  Unit(
    id: 'kilometre_per_hour',
    name: 'Kilometre per hour',
    symbol: 'km/h',
    category: UnitCategory.speed,
    toBase: '1000/3600',
    aliases: ['kilometres per hour', 'kilometers per hour', 'km/h', 'kph', 'kmh'],
  ),
  Unit(
    id: 'mile_per_hour',
    name: 'Mile per hour',
    symbol: 'mph',
    category: UnitCategory.speed,
    toBase: '63360*0.0254/3600',
    aliases: ['miles per hour', 'mph'],
  ),
  Unit(
    id: 'foot_per_second',
    name: 'Foot per second',
    symbol: 'ft/s',
    category: UnitCategory.speed,
    toBase: '12*0.0254',
    aliases: ['feet per second', 'ft/s', 'fps'],
  ),
  Unit(
    id: 'knot',
    name: 'Knot',
    symbol: 'kn',
    category: UnitCategory.speed,
    toBase: '1852/3600',
    aliases: ['knots', 'kt', 'kts'],
  ),
  Unit(
    id: 'mach',
    name: 'Mach (sea level)',
    symbol: 'Ma',
    category: UnitCategory.speed,
    toBase: '340.29',
    aliases: ['mach'],
    note: 'The speed of sound depends on temperature. This is the value '
        'at sea level in the standard atmosphere; it falls to about '
        '295 m/s at cruising altitude.',
  ),
  Unit(
    id: 'speed_of_light',
    name: 'Speed of light',
    symbol: 'c',
    category: UnitCategory.speed,
    toBase: '299792458',
    aliases: ['light speed', 'lightspeed'],
  ),
];

const angleUnits = <Unit>[
  Unit(
    id: 'radian',
    name: 'Radian',
    symbol: 'rad',
    category: UnitCategory.angle,
    toBase: '1',
    aliases: ['radians', 'rad', 'rads'],
  ),
  Unit(
    id: 'degree',
    name: 'Degree',
    symbol: '°',
    category: UnitCategory.angle,
    // Involves π, so angle conversions are approximate by nature —
    // unlike every other category here.
    toBase: 'pi/180',
    aliases: ['degrees', 'deg', 'degs'],
  ),
  Unit(
    id: 'gradian',
    name: 'Gradian',
    symbol: 'grad',
    category: UnitCategory.angle,
    toBase: 'pi/200',
    aliases: ['gradians', 'gon', 'grade'],
  ),
  Unit(
    id: 'turn',
    name: 'Turn',
    symbol: 'tr',
    category: UnitCategory.angle,
    toBase: '2*pi',
    aliases: ['turns', 'revolution', 'revolutions', 'rev'],
  ),
  Unit(
    id: 'arcminute',
    name: 'Arcminute',
    symbol: '′',
    category: UnitCategory.angle,
    toBase: 'pi/10800',
    aliases: ['arcminutes', 'arcmin', 'minute of arc'],
  ),
  Unit(
    id: 'arcsecond',
    name: 'Arcsecond',
    symbol: '″',
    category: UnitCategory.angle,
    toBase: 'pi/648000',
    aliases: ['arcseconds', 'arcsec', 'second of arc'],
  ),
  Unit(
    id: 'milliradian',
    name: 'Milliradian',
    symbol: 'mrad',
    category: UnitCategory.angle,
    toBase: '0.001',
    aliases: ['milliradians', 'mrad', 'mil'],
  ),
];

const frequencyUnits = <Unit>[
  Unit(
    id: 'hertz',
    name: 'Hertz',
    symbol: 'Hz',
    category: UnitCategory.frequency,
    toBase: '1',
    aliases: ['hz'],
  ),
  Unit(
    id: 'kilohertz',
    name: 'Kilohertz',
    symbol: 'kHz',
    category: UnitCategory.frequency,
    toBase: '1000',
    aliases: ['khz'],
  ),
  Unit(
    id: 'megahertz',
    name: 'Megahertz',
    symbol: 'MHz',
    category: UnitCategory.frequency,
    toBase: '1000000',
    aliases: ['mhz'],
  ),
  Unit(
    id: 'gigahertz',
    name: 'Gigahertz',
    symbol: 'GHz',
    category: UnitCategory.frequency,
    toBase: '10^9',
    aliases: ['ghz'],
  ),
  Unit(
    id: 'terahertz',
    name: 'Terahertz',
    symbol: 'THz',
    category: UnitCategory.frequency,
    toBase: '10^12',
    aliases: ['thz'],
  ),
  Unit(
    id: 'rpm',
    name: 'Revolutions per minute',
    symbol: 'rpm',
    category: UnitCategory.frequency,
    toBase: '1/60',
    aliases: ['revolutions per minute', 'rpm', 'bpm', 'beats per minute'],
  ),
];
