/// Length, area and volume.
///
/// Every imperial and US customary unit here traces back to the
/// international yard and pound agreement of 1959, which defines the inch
/// as exactly 0.0254 metres. Writing each unit as its definition in terms
/// of that one number — rather than as a rounded decimal — is what keeps
/// a mile exactly 5280 feet after conversion.
library;

import '../unit.dart';

const lengthUnits = <Unit>[
  Unit(
    id: 'metre',
    name: 'Metre',
    symbol: 'm',
    category: UnitCategory.length,
    toBase: '1',
    aliases: ['meter', 'metres', 'meters', 'm'],
  ),
  Unit(
    id: 'kilometre',
    name: 'Kilometre',
    symbol: 'km',
    category: UnitCategory.length,
    toBase: '1000',
    aliases: ['kilometer', 'kilometres', 'kilometers', 'km'],
  ),
  Unit(
    id: 'centimetre',
    name: 'Centimetre',
    symbol: 'cm',
    category: UnitCategory.length,
    toBase: '0.01',
    aliases: ['centimeter', 'centimetres', 'centimeters', 'cm'],
  ),
  Unit(
    id: 'millimetre',
    name: 'Millimetre',
    symbol: 'mm',
    category: UnitCategory.length,
    toBase: '0.001',
    aliases: ['millimeter', 'millimetres', 'millimeters', 'mm'],
  ),
  Unit(
    id: 'micrometre',
    name: 'Micrometre',
    symbol: 'µm',
    category: UnitCategory.length,
    toBase: '0.000001',
    aliases: ['micrometer', 'micron', 'microns', 'um'],
  ),
  Unit(
    id: 'nanometre',
    name: 'Nanometre',
    symbol: 'nm',
    category: UnitCategory.length,
    toBase: '1/10^9',
    aliases: ['nanometer', 'nanometres', 'nanometers', 'nm'],
  ),
  Unit(
    id: 'angstrom',
    name: 'Ångström',
    symbol: 'Å',
    category: UnitCategory.length,
    toBase: '1/10^10',
    aliases: ['angstrom', 'angstroms'],
  ),
  Unit(
    id: 'inch',
    name: 'Inch',
    symbol: 'in',
    category: UnitCategory.length,
    toBase: '0.0254',
    aliases: ['inches', 'in', '"'],
  ),
  Unit(
    id: 'foot',
    name: 'Foot',
    symbol: 'ft',
    category: UnitCategory.length,
    toBase: '12*0.0254',
    aliases: ['feet', 'ft', "'"],
  ),
  Unit(
    id: 'yard',
    name: 'Yard',
    symbol: 'yd',
    category: UnitCategory.length,
    toBase: '36*0.0254',
    aliases: ['yards', 'yd'],
  ),
  Unit(
    id: 'mile',
    name: 'Mile',
    symbol: 'mi',
    category: UnitCategory.length,
    // 1760 yards.
    toBase: '63360*0.0254',
    aliases: ['miles', 'mi'],
  ),
  Unit(
    id: 'nautical_mile',
    name: 'Nautical mile',
    symbol: 'nmi',
    category: UnitCategory.length,
    toBase: '1852',
    // Deliberately not aliased to "nm": in a calculator that also does
    // nanometres, that abbreviation is a trap.
    aliases: ['nautical miles', 'nmi'],
  ),
  Unit(
    id: 'thou',
    name: 'Thou',
    symbol: 'thou',
    category: UnitCategory.length,
    toBase: '0.0254/1000',
    aliases: ['mil', 'mils', 'thousandth of an inch'],
  ),
  Unit(
    id: 'hand',
    name: 'Hand',
    symbol: 'hh',
    category: UnitCategory.length,
    toBase: '4*0.0254',
    aliases: ['hands'],
  ),
  Unit(
    id: 'fathom',
    name: 'Fathom',
    symbol: 'ftm',
    category: UnitCategory.length,
    toBase: '72*0.0254',
    aliases: ['fathoms'],
  ),
  Unit(
    id: 'rod',
    name: 'Rod',
    symbol: 'rd',
    category: UnitCategory.length,
    toBase: '198*0.0254',
    aliases: ['rods', 'perch', 'pole'],
  ),
  Unit(
    id: 'chain',
    name: 'Chain',
    symbol: 'ch',
    category: UnitCategory.length,
    toBase: '792*0.0254',
    aliases: ['chains'],
  ),
  Unit(
    id: 'furlong',
    name: 'Furlong',
    symbol: 'fur',
    category: UnitCategory.length,
    toBase: '7920*0.0254',
    aliases: ['furlongs'],
  ),
  Unit(
    id: 'point',
    name: 'Point (typographic)',
    symbol: 'pt',
    category: UnitCategory.length,
    toBase: '0.0254/72',
    aliases: ['points', 'pt'],
  ),
  Unit(
    id: 'pica',
    name: 'Pica',
    // Not "pc", which this catalog gives to the parsec.
    symbol: 'pica',
    category: UnitCategory.length,
    toBase: '0.0254/6',
    aliases: ['picas'],
  ),
  Unit(
    id: 'astronomical_unit',
    name: 'Astronomical unit',
    symbol: 'au',
    category: UnitCategory.length,
    toBase: '149597870700',
    aliases: ['astronomical units', 'au', 'ua'],
  ),
  Unit(
    id: 'light_year',
    name: 'Light year',
    symbol: 'ly',
    category: UnitCategory.length,
    // The speed of light times a Julian year, both exact by definition.
    toBase: '299792458*365.25*86400',
    aliases: ['light years', 'lightyear', 'lightyears', 'ly'],
  ),
  Unit(
    id: 'parsec',
    name: 'Parsec',
    symbol: 'pc',
    category: UnitCategory.length,
    // Defined by an angle, so this one is genuinely irrational and the
    // result comes back approximate rather than exact.
    toBase: '648000/pi*149597870700',
    aliases: ['parsecs'],
  ),
];

const areaUnits = <Unit>[
  Unit(
    id: 'square_metre',
    name: 'Square metre',
    symbol: 'm²',
    category: UnitCategory.area,
    toBase: '1',
    aliases: ['square meter', 'square metres', 'square meters', 'm2', 'sqm'],
  ),
  Unit(
    id: 'square_kilometre',
    name: 'Square kilometre',
    symbol: 'km²',
    category: UnitCategory.area,
    toBase: '1000^2',
    aliases: ['square kilometer', 'square kilometres', 'km2'],
  ),
  Unit(
    id: 'square_centimetre',
    name: 'Square centimetre',
    symbol: 'cm²',
    category: UnitCategory.area,
    toBase: '0.01^2',
    aliases: ['square centimeter', 'square centimetres', 'cm2'],
  ),
  Unit(
    id: 'square_millimetre',
    name: 'Square millimetre',
    symbol: 'mm²',
    category: UnitCategory.area,
    toBase: '0.001^2',
    aliases: ['square millimeter', 'square millimetres', 'mm2'],
  ),
  Unit(
    id: 'hectare',
    name: 'Hectare',
    symbol: 'ha',
    category: UnitCategory.area,
    toBase: '10000',
    aliases: ['hectares', 'ha'],
  ),
  Unit(
    id: 'are',
    name: 'Are',
    symbol: 'a',
    category: UnitCategory.area,
    toBase: '100',
    aliases: ['ares'],
  ),
  Unit(
    id: 'square_inch',
    name: 'Square inch',
    symbol: 'in²',
    category: UnitCategory.area,
    toBase: '0.0254^2',
    aliases: ['square inches', 'sq in', 'in2'],
  ),
  Unit(
    id: 'square_foot',
    name: 'Square foot',
    symbol: 'ft²',
    category: UnitCategory.area,
    toBase: '(12*0.0254)^2',
    aliases: ['square feet', 'sq ft', 'ft2'],
  ),
  Unit(
    id: 'square_yard',
    name: 'Square yard',
    symbol: 'yd²',
    category: UnitCategory.area,
    toBase: '(36*0.0254)^2',
    aliases: ['square yards', 'sq yd', 'yd2'],
  ),
  Unit(
    id: 'acre',
    name: 'Acre',
    symbol: 'ac',
    category: UnitCategory.area,
    // 4840 square yards.
    toBase: '4840*(36*0.0254)^2',
    aliases: ['acres', 'ac'],
  ),
  Unit(
    id: 'square_mile',
    name: 'Square mile',
    symbol: 'mi²',
    category: UnitCategory.area,
    toBase: '(63360*0.0254)^2',
    aliases: ['square miles', 'sq mi', 'mi2'],
  ),
  Unit(
    id: 'barn',
    name: 'Barn',
    symbol: 'b',
    category: UnitCategory.area,
    toBase: '1/10^28',
    aliases: ['barns'],
  ),
];

const volumeUnits = <Unit>[
  Unit(
    id: 'cubic_metre',
    name: 'Cubic metre',
    symbol: 'm³',
    category: UnitCategory.volume,
    toBase: '1',
    aliases: ['cubic meter', 'cubic metres', 'cubic meters', 'm3'],
  ),
  Unit(
    id: 'litre',
    name: 'Litre',
    symbol: 'L',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.001',
    aliases: ['liter', 'litres', 'liters', 'l'],
  ),
  Unit(
    id: 'millilitre',
    name: 'Millilitre',
    symbol: 'mL',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.000001',
    aliases: ['milliliter', 'millilitres', 'milliliters', 'ml', 'cc'],
  ),
  Unit(
    id: 'centilitre',
    name: 'Centilitre',
    symbol: 'cL',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.00001',
    aliases: ['centiliter', 'centilitres', 'cl'],
  ),
  Unit(
    id: 'decilitre',
    name: 'Decilitre',
    symbol: 'dL',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.0001',
    aliases: ['deciliter', 'decilitres', 'dl'],
  ),
  Unit(
    id: 'hectolitre',
    name: 'Hectolitre',
    symbol: 'hL',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.1',
    aliases: ['hectoliter', 'hectolitres', 'hl'],
  ),
  Unit(
    id: 'cubic_centimetre',
    name: 'Cubic centimetre',
    symbol: 'cm³',
    category: UnitCategory.volume,
    toBase: '0.01^3',
    aliases: ['cubic centimeter', 'cubic centimetres', 'cm3'],
  ),
  Unit(
    id: 'cubic_inch',
    name: 'Cubic inch',
    symbol: 'in³',
    category: UnitCategory.volume,
    toBase: '0.0254^3',
    aliases: ['cubic inches', 'cu in', 'in3'],
  ),
  Unit(
    id: 'cubic_foot',
    name: 'Cubic foot',
    symbol: 'ft³',
    category: UnitCategory.volume,
    toBase: '(12*0.0254)^3',
    aliases: ['cubic feet', 'cu ft', 'ft3'],
  ),
  Unit(
    id: 'cubic_yard',
    name: 'Cubic yard',
    symbol: 'yd³',
    category: UnitCategory.volume,
    toBase: '(36*0.0254)^3',
    aliases: ['cubic yards', 'cu yd', 'yd3'],
  ),
  Unit(
    id: 'gallon_us',
    name: 'Gallon (US)',
    symbol: 'gal',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    // Defined as exactly 231 cubic inches.
    toBase: '231*0.0254^3',
    aliases: ['us gallon', 'us gallons', 'gallon', 'gallons', 'gal'],
    note: 'A US gallon is about 17% smaller than an imperial gallon.',
  ),
  Unit(
    id: 'quart_us',
    name: 'Quart (US)',
    symbol: 'qt',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/4',
    aliases: ['us quart', 'us quarts', 'quart', 'quarts', 'qt'],
  ),
  Unit(
    id: 'pint_us',
    name: 'Pint (US)',
    symbol: 'pt',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/8',
    aliases: ['us pint', 'us pints', 'pint', 'pints'],
    note: 'A US pint is 473 mL; an imperial pint is 568 mL.',
  ),
  Unit(
    id: 'fluid_ounce_us',
    name: 'Fluid ounce (US)',
    symbol: 'fl oz',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/128',
    aliases: ['us fluid ounce', 'us fluid ounces', 'fluid ounce', 'fluid ounces', 'fl oz'],
  ),
  Unit(
    id: 'gallon_imperial',
    name: 'Gallon (imperial)',
    symbol: 'gal',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609',
    aliases: ['gallon', 'gallons', 'gal', 'imperial gallon', 'imperial gallons', 'uk gallon', 'uk gallons'],
  ),
  Unit(
    id: 'quart_imperial',
    name: 'Quart (imperial)',
    symbol: 'qt',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609/4',
    aliases: ['quart', 'quarts', 'qt', 'imperial quart', 'imperial quarts', 'uk quart'],
  ),
  Unit(
    id: 'pint_imperial',
    name: 'Pint (imperial)',
    symbol: 'pt',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609/8',
    aliases: ['pint', 'pints', 'imperial pint', 'imperial pints', 'uk pint', 'uk pints'],
  ),
  Unit(
    id: 'fluid_ounce_imperial',
    name: 'Fluid ounce (imperial)',
    symbol: 'fl oz',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609/160',
    aliases: ['fluid ounce', 'fluid ounces', 'fl oz', 'imperial fluid ounce', 'imperial fluid ounces', 'uk fluid ounce'],
  ),
  Unit(
    id: 'barrel_oil',
    name: 'Barrel (oil)',
    symbol: 'bbl',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '42*231*0.0254^3',
    aliases: ['barrel', 'barrels', 'oil barrel', 'bbl'],
  ),
  // --- Cooking measures. These are volume units like any other, so they
  // convert to millilitres and to each other without a special case.
  Unit(
    id: 'cup_us_customary',
    name: 'Cup (US customary)',
    symbol: 'cup',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/16',
    aliases: ['cup', 'cups', 'us cup', 'us cups'],
    note: 'US recipes usually mean this cup: 236.6 mL. Nutrition labels '
        'use the legal cup of 240 mL instead.',
  ),
  Unit(
    id: 'cup_us_legal',
    name: 'Cup (US legal)',
    symbol: 'cup',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '0.00024',
    aliases: ['legal cup', 'nutrition cup'],
    note: 'The 240 mL cup used on US nutrition labels.',
  ),
  Unit(
    id: 'cup_metric',
    name: 'Cup (metric)',
    symbol: 'cup',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.00025',
    aliases: ['cup', 'cups', 'metric cup', 'metric cups'],
    note: 'The 250 mL cup used in Australia, New Zealand and the UK.',
  ),
  Unit(
    id: 'tablespoon_us',
    name: 'Tablespoon (US)',
    symbol: 'tbsp',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/256',
    aliases: ['tablespoon', 'tablespoons', 'tbsp', 'us tablespoon'],
  ),
  Unit(
    id: 'tablespoon_metric',
    name: 'Tablespoon (metric)',
    symbol: 'tbsp',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.000015',
    aliases: ['tablespoon', 'tablespoons', 'tbsp', 'metric tablespoon', 'metric tablespoons'],
  ),
  Unit(
    id: 'tablespoon_australian',
    name: 'Tablespoon (Australian)',
    symbol: 'tbsp',
    system: UnitSystem.australian,
    category: UnitCategory.volume,
    toBase: '0.00002',
    aliases: ['tablespoon', 'tablespoons', 'tbsp', 'australian tablespoon', 'australian tablespoons', 'aussie tablespoon'],
    note: 'Australian tablespoons hold 20 mL — a third more than every '
        'other tablespoon. Worth checking before baking.',
  ),
  Unit(
    id: 'tablespoon_imperial',
    name: 'Tablespoon (imperial)',
    symbol: 'tbsp',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609/256',
    aliases: ['tablespoon', 'tablespoons', 'tbsp', 'imperial tablespoon', 'uk tablespoon'],
  ),
  Unit(
    id: 'teaspoon_us',
    name: 'Teaspoon (US)',
    symbol: 'tsp',
    system: UnitSystem.us,
    category: UnitCategory.volume,
    toBase: '231*0.0254^3/768',
    aliases: ['teaspoon', 'teaspoons', 'tsp', 'us teaspoon'],
  ),
  Unit(
    id: 'teaspoon_metric',
    name: 'Teaspoon (metric)',
    symbol: 'tsp',
    system: UnitSystem.metric,
    category: UnitCategory.volume,
    toBase: '0.000005',
    aliases: ['teaspoon', 'teaspoons', 'tsp', 'metric teaspoon', 'metric teaspoons'],
  ),
  Unit(
    id: 'teaspoon_imperial',
    name: 'Teaspoon (imperial)',
    symbol: 'tsp',
    system: UnitSystem.imperial,
    category: UnitCategory.volume,
    toBase: '0.00454609/768',
    aliases: ['teaspoon', 'teaspoons', 'tsp', 'imperial teaspoon', 'uk teaspoon'],
  ),
];
